package br.comloginA3.view;

import br.comloginA3.DAO.Conexao;
import br.comloginA3.controller.LoginController;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author guilh
 */
public class LoginA3_View extends javax.swing.JFrame {

    /**
     * Creates new form LoginA3_View
     */
    public LoginA3_View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextFieldEmailLogin = new javax.swing.JFormattedTextField();
        jPasswordFieldSenhaLogin = new javax.swing.JPasswordField();
        BotaoLogar = new javax.swing.JButton();
        BotaoRealizarCadastro = new javax.swing.JButton();
        BotaoEsqueceuSenha = new javax.swing.JButton();
        Tela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFormattedTextFieldEmailLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldEmailLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldEmailLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 470, 40));
        getContentPane().add(jPasswordFieldSenhaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 470, 40));

        BotaoLogar.setContentAreaFilled(false);
        BotaoLogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLogarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 120, 50));

        BotaoRealizarCadastro.setContentAreaFilled(false);
        BotaoRealizarCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoRealizarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRealizarCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoRealizarCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 170, 20));

        BotaoEsqueceuSenha.setForeground(new java.awt.Color(51, 51, 255));
        BotaoEsqueceuSenha.setText("Esqueceu a senha?");
        BotaoEsqueceuSenha.setContentAreaFilled(false);
        BotaoEsqueceuSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(BotaoEsqueceuSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        Tela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Realizar Cadastro (2).png"))); // NOI18N
        Tela.setText("jLabel1");
        getContentPane().add(Tela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 801, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFieldEmailLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldEmailLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldEmailLoginActionPerformed

    private void BotaoLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLogarActionPerformed
        if(jFormattedTextFieldEmailLogin.getText().matches("") || jPasswordFieldSenhaLogin.getText().matches("")){
            JOptionPane.showConfirmDialog(rootPane, "Preencha todos os campos");
        }else {
                LoginController login = new LoginController();
                login.LoginUsuario(this);
        }
        
    }//GEN-LAST:event_BotaoLogarActionPerformed

    private void BotaoRealizarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRealizarCadastroActionPerformed
        LoginA3_ViewCadastro BotaoRealizarCadastro = new LoginA3_ViewCadastro(this);
        BotaoRealizarCadastro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotaoRealizarCadastroActionPerformed

    public JFormattedTextField getjFormattedTextFieldLogin() {
        return jFormattedTextFieldEmailLogin;
    }

    public void setjFormattedTextFieldLogin(JFormattedTextField jFormattedTextFieldLogin) {
        this.jFormattedTextFieldEmailLogin = jFormattedTextFieldLogin;
    }

    public JPasswordField getjPasswordFieldSenhaLogin() {
        return jPasswordFieldSenhaLogin;
    }

    public void setjPasswordFieldSenhaLogin(JPasswordField jPasswordFieldSenhaLogin) {
        this.jPasswordFieldSenhaLogin = jPasswordFieldSenhaLogin;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginA3_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginA3_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginA3_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginA3_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginA3_View().setVisible(true);
            }
        });
        new Conexao();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoEsqueceuSenha;
    private javax.swing.JButton BotaoLogar;
    private javax.swing.JButton BotaoRealizarCadastro;
    private javax.swing.JLabel Tela;
    private javax.swing.JFormattedTextField jFormattedTextFieldEmailLogin;
    private javax.swing.JPasswordField jPasswordFieldSenhaLogin;
    // End of variables declaration//GEN-END:variables

    public Object getjTextFieldLogin() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public Object getjTextFieldEmailLogin() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public Object jFormattedTextFieldEmailLogin() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
