package br.comloginA3.view;

import br.comloginA3.controller.LoginController;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;


public class LoginA3_ViewCadastro extends javax.swing.JFrame {

    /**
     * Creates new form LoginA3_View
     * @param view
     */
    public LoginA3_ViewCadastro(LoginA3_View view) {
        this.view = view;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextFieldNome = new javax.swing.JFormattedTextField();
        jPasswordFieldConfSenha = new javax.swing.JPasswordField();
        BotaoLogar = new javax.swing.JButton();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jFormattedTextFieldEmail = new javax.swing.JFormattedTextField();
        Tela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFormattedTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 470, 40));
        getContentPane().add(jPasswordFieldConfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 470, 40));

        BotaoLogar.setContentAreaFilled(false);
        BotaoLogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLogarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 100, 50));
        getContentPane().add(jPasswordFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 470, 40));

        jFormattedTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 470, 40));

        Tela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Tela de Cadastro.png"))); // NOI18N
        Tela.setText("jLabel1");
        Tela.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                WindowClose(evt);
            }
        });
        getContentPane().add(Tela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 801, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldNomeActionPerformed

    private void BotaoLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLogarActionPerformed
        
        if(jFormattedTextFieldNome.getText().matches("") || jFormattedTextFieldEmail.getText().matches("")
        || jPasswordFieldSenha.getText().matches("")){
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos");
        }else{
            LoginController cadastro = new LoginController();
            cadastro.cadastroUusuario(this);
            JOptionPane.showMessageDialog(rootPane, "Cadastro realizado!");
            this.dispose();
        }
    }//GEN-LAST:event_BotaoLogarActionPerformed

    private void jFormattedTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldEmailActionPerformed

    private void WindowClose(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_WindowClose
        view.setVisible(true);
    }//GEN-LAST:event_WindowClose

    public JFormattedTextField getjFormattedTextFieldEmail() {
        return jFormattedTextFieldEmail;
    }

    public void setjFormattedTextFieldEmail(JFormattedTextField jFormattedTextFieldEmail) {
        this.jFormattedTextFieldEmail = jFormattedTextFieldEmail;
    }

    public JFormattedTextField getjFormattedTextFieldNome() {
        return jFormattedTextFieldNome;
    }

    public void setjFormattedTextFieldNome(JFormattedTextField jFormattedTextFieldNome) {
        this.jFormattedTextFieldNome = jFormattedTextFieldNome;
    }

    public JPasswordField getjPasswordFieldConfSenha() {
        return jPasswordFieldConfSenha;
    }

    public void setjPasswordFieldConfSenha(JPasswordField jPasswordFieldConfSenha) {
        this.jPasswordFieldConfSenha = jPasswordFieldConfSenha;
    }

    public JPasswordField getjPasswordFieldSenha() {
        return jPasswordFieldSenha;
    }

    public void setjPasswordFieldSenha(JPasswordField jPasswordFieldSenha) {
        this.jPasswordFieldSenha = jPasswordFieldSenha;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginA3_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginA3_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginA3_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginA3_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginA3_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoLogar;
    private javax.swing.JLabel Tela;
    private javax.swing.JFormattedTextField jFormattedTextFieldEmail;
    private javax.swing.JFormattedTextField jFormattedTextFieldNome;
    private javax.swing.JPasswordField jPasswordFieldConfSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    // End of variables declaration//GEN-END:variables

    private Object jTextFieldNome() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private Object jTextFieldEmail() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private Object jFormattedTextFieldEmail() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    private LoginA3_View view;
}
